#######################################################################################
# Book settings (https://jupyterbook.org/customize/config.html)
title: Allen Brain Cell Atlas - Data Access
author: Allen Institute
copyright: "2023"
logo: ./images/allen_logo.jpeg
exclude_patterns: [_build, .DS_Store]   # Patterns to skip when building the book.
only_build_toc_files: true              # Auto-exclude files not in the toc
bibtex_bibfiles:
  - references.bib

#######################################################################################
# Execution settings (https://jupyterbook.org/content/execute.html)
execute:
  execute_notebooks: off                # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout: 3000                         # The maximum time (in seconds) each notebook cell is allowed to run.
  exclude_patterns: [.github/*]         # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  use_issues_button: true               # Whether to add an "open an issue" button
  use_repository_button: true           # Whether to add a link to your repository button

#######################################################################################
# Launch button settings
repository:
  url                       : https://github.com/AllenInstitute/abc_atlas_access   # The URL to your book's repository
  path_to_book              : "."                                                  # A path to your book's folder, relative to the repository root.
  branch                    : main                                                 # Which branch of the repository should be used when creating links