# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Allen Brain Cell Atlas - Data Access
author: Allen Institute
logo: allen_logo.jpeg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
# execute:
#   execute_notebooks: force
################
# Sphinx customizations
sphinx:
  config:
    # html_extra_path: ["assets"]
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# Execution settings
execute:
  timeout: 3000
  exclude_patterns:
    - .github/*
  execute_notebooks: auto

only_build_toc_files: true
##############
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
